sudo: false
language: java
jdk:
- openjdk8
- openjdk11
script: make default
jobs:
  include:
  - stage: mvn deploy
    jdk: openjdk8
    deploy:
      skip_cleanup: true
      provider: script
      script: bash ./scripts/mvn_deploy.sh
env:
  global:
  - secure: NpoU1FEF+CihpUE1GfqhLA/qPxbwwJQk1z3v7JNxwLrI6ZTUsb6JauIsSwRELKSgDrz1t953zlFmAo/BVo+cxBDVH2vxBObYP8voAcjaH0W0c6BfYKUrrAxTTqWly+Iy06Hn9nInLd8+2fzzIcEuRQ5mEbEwSKQjz4b/f4qe6Wez+PiGY0hAmxaOaB0/0I2C/hkJJcKLq54/d3Su+06iI1PbchtKbo0h079I6vRWlh4kCf8Orq51fAk59zCDVp+//ERDYsI64lJ0UqSaK+vP54xz9HZsOE5ELoi1zfUcLP3Xv3UbpFHZ7zRZwEDkGMnGJSrhtk5R7zbNLOlwkb+k+v1hE4ZNpw8cFVJzmE3akZ56q1VjftOpPMSZlhKJlJcHLzMqLEtCdxu03+nsxIe6XqC2pahjn4pgtfj+jcuUphH7B0jZyUoxzlQzEru/EOAY5sAJEFANpxOvn0hX1crQXXREmpduVDH/TjwtcEsMd+4ubW0UYt3/VdaDhuNFppPeR/KL21/+C3CvhjJToGkDdhneWTypSJmDrqV8mewIbhKuhN3lurpWHCyCY5KTPlGWJzXTzy3kjmguQ+urvDw4ipFEBPFQWeEOy5y45DVnu62P4y8Nxuf+sQDsS3Foc4lNAC+scc9klD0BF2Ah3I4hE9ZtxqDsGKtOcMmoH1wajwo=
  - secure: caBEQwbQsxtRgsUuI4m8q7JIfjMOLvfly4uMHEazLTrgxxz34vn0YM4leIyt70I/yUaWRqSQRWhd/zKtZrPClhzKjd1AxhFf7xda316Lew+sdaMbtojjKCDdQtin0O0TSEW6OTpeyJTib4Ifu4eC2biS5yqK9roBt8kxaCs6gFx26g2BWAEUu/GThswz+0SZfm2auWxtSjbkEjqxTyU07gli8qcBjdvVtwIhQFNoK+YLXuwv0vh2x/9LiTOcI8YCMcBxzn+Yn8gnU1FbwYjKqzrX423gRsvdJTJ5ILu8BGfq1Uqdod+Z6LBokJwVY757qSC3BFcirDBXRdooQk2r2SVrwxmzTZa1yPV6f1G/ZaS/0xGhKCELcEKnSS517BLJYrCWuyNVkT1OL2qKzyHHxrpe6sYg7w1Vm5L+JQTw8oRAoMl2Q2bu+tPL27yoyqYIeSO0PTWCYHH4XgTitZ2k66/l6Hv8fOf1HHyIsU+ogpzU9Z6g3mtQLLhWG74tpb+lpLpdwq/WGGFBXkyqhJrTCGHra2l72iTxB+XlmYbNM7bMFoN7MkCWzYmCwuGCMbHReVjg5cuHYJL7qq+JOJUor55XZwYYKu8o8UaGxvZlSsCRF+PJK7MmQmDFX3rn9xOD0wDb9/SunKrGy2hp5+33SlfswslxlBUDIzpL90hdy6c=
before_install:
- openssl aes-256-cbc -K $encrypted_1cfff19a9ef3_key -iv $encrypted_1cfff19a9ef3_iv
  -in scripts/codesigning.asc.enc -out scripts/codesigning.asc -d
