sudo: false
language: java
jdk:
- oraclejdk8
- openjdk11
- openjdk-ea
jobs:
  include:
  - stage: deploy
    jdk: oraclejdk8
    script:
    - "[ -z $TRAVIS_TAG ] && ./scripts/mvn_deploy.sh"
script: make default
env:
  global:
  - secure: OAh+xh8LU7v7tDu6aQ5Q38MagT8mJPqEXYpJyUhYXthxwvmO/SYuw4OEiLZtkNCIWRUyAIb4MRmy4wK7SAlSHYbGF9Ka7y+DUaeOrGVa8l2rhGwvEJgbWD0X+BYoxRt4NPgwHEdI/VdxjSEbPKkYNAM4xBzTw0oR6vgxQulpcUQ9bfj4l01N+ewTHFTR6xeJO4FPU1TvsDsgQCCr2LHL3vfCrNf62MhUz1jPKm8QCZnjcjXetyFPxsXOfr+cA29S24QbZSX2Z+vNGrJqKn5K/+Wpu95Vod3iuQG1wMgqfQfhqNIvA2yR2dqXF1oyDggJw/EENbzvDarcqQHUCzqjpm8igNpt7YA/UyB+i6rnlwcodgfqS6eCzkOPOox5K3ZtfTTIaJEp4QMJKueqHo+oosr93J6HMNEOAyJxq2IYhz1IO9OJIypFLqDRxvhayOEKFeo/tWiOEtKh02pdAcPAwG2Xp1cCcJ/SH9VjZmfv1sl4UmBm/GGdIFeEAC20NBsBumjw+tf2qrpNIekB++iVab3WTK+pki0vTOG3wrKgFw5Dw9/HriYzXtIxMkUu7LBRx/pdC2P0EyzNqsWRWVg9KXqcT5GKXuqf+qlzyWPzObiC6CG6Ss5tpl7daNV+IO+X+Lll6qrAyMdB2UNJeTPrMGBVy5DRbvyTtFuZO2sAhiU=
  - secure: iWF79qI09VfwHJK3Yut0Fg4ujfeN0wo/bxTi4GTI0/ZGxxSfJNNe+2Vep9GnFbHpDq0Ch1jEw5LxfX5uViSIJhGXDSKGr5rVL0AJQ3aC64Jg/rESL/RZE43ck0tk/mmbCJgm5vJZ1UF7RryFtMqfiQfVV1sQHP7EGl4iBoMLv1nizM3vt7vCbxOuw5HdIvLkEyHJQSM8PxMEx+aSqdG49svlhGO/zis+dZW9yGAB4WvkjMP+9seanfMvaAHN/ByKmvs0JmJL717ybiAdD4qoUJmOQOx5P/HVgZwfkLWX4gR37+DSKBIjBGKC9Qz3r0qT9Q3LlqLwNXD8QvZn076ZchlJA/nxX8IqJFy+NaHMXmAO8YtCDQjW/lXNJiBM43/2wBj23TKuIco7M/PRmfhrOjgT3VfvYm+fQ/xer4yptT4lyfq8Hl21vaJkjRJDfILPI47gH0b1nQYs/hEsGd3q3pNeMp+oLtUqxBk7EX1zNn6ctujG7nyZ71Pvfl1iXQRm7YrQBjIsH6TqF9/tep/OS5/MeEhpLCW8ltlH3x/kHJnM8OgrhOdrewQRfRclSf/MBR9Rzn/VHFQcHlCukUJD1MciULsLVdqo6/G6NbWCWdV3q+YgMwOVZ5HehO5WNKxmnWn2QrgJTNJN3SN1aADekAAtaDnlORZL2FaFgJHZd8o=
before_install:
- openssl aes-256-cbc -K $encrypted_365192ac843a_key -iv $encrypted_365192ac843a_iv
  -in scripts/codesigning.asc.enc -out scripts/codesigning.asc -d
