# Please update /.templates/python/.travis.yml in the cucumber/cucumber monorepo
# and sync:
#
#     source scripts/functions.sh && rsync_files
#
sudo: false
language: python
python:
  - "3.7-dev"
  - "2.7"
  - "3.6"
  - "3.5"
  - "pypy"
  - "pypy3"

matrix:
  allow_failures:
    - python: "pypy3"

install: pip install tox-travis
script:  tox
