language: go
sudo: false

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - "tip"

cache:
  directories:
    - protobuf-3.6.0

install:
  - if [ ! -d "$PWD/protobuf-3.6.0" ]; then ./install_protobuf.sh 3.6.0; fi
  - export PATH=$PATH:$PWD/protobuf-3.6.0/src

script: make default
