language: ruby

rvm:
  - 2.3
  - 2.2
  - jruby

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5373e574ed4e88026838
    on_success: always
    on_failure: always
    on_start: never
