sudo: false
language: java
jdk:
- oraclejdk8
- openjdk11
jobs:
  include:
  - stage: deploy
    jdk: oraclejdk8
    script:
    - ./scripts/mvn_deploy.sh
script: make default
env:
  global:
  - secure: YnNRLvXpS/lQg85p9h97FcdXjtOpKBgLTVCABRHsf7iXEoOfy6SgVFsjrv9uF8oGQUoL7cAC7OdcBVD3dgCJhCl3W09mxVfA/HjCEYMurG+T1v54TiOpVSor07xPKYQFUufR//0slAvyy6358t1W7a4H7Kss2HCZz/lxZD5XS7OG+2aqHEu37gS6sN7VIZhwA7HXATIgyX8ZSdKjEHjhVmbSk7UEIH8yrIihRxJ4dCR6LIU+mgYypM3LccPwiBXmEMR5vnQ4gtt5NHCWND6icVu+05hNvJXfe4CYXYlRGoAy6OcUFlUonnc1Hl71d5yUcFWHLWWjGUo0AHBWxbH4UD6iVRiFvlqw+bwU2jTiIsKtcxTbi85soJs8yUlLmCM8r4pxvGLJmmY6m2qUuDE1bnkZU0kCgVh5NB67mPHDk7FxVYy/jVyVufCe3STFktotVXDT+WF0X9x+we0FKFtF52PL7Lajmswatqkdlx1tjfphqcufup8C9bbeMnbKpaINAE7jcXkgxSrrcheOqAdLNgdzx1AKs4v/JJ5hDHjayCxeB9LDK+nioMoGyLRLz2u49vVMAFij7XtKtsw+B4TFIji/fAgWkTzJulRIhiy9uAn3NRlU0rHWo565aJuL0fF9PQ6K2QdhoJjP7Xp6qgh2ugigr0j1XQ6ymWF3pOvgUFU=
  - secure: NS2Cd2+0BvkTWZBcD7VGd6Z4EE1s2O3Z3bckfag4IOLKDPb7jPA2CYGRv3GQBSzqmuhQwJ/yefsJfelk33XlOWG8dfNU2tuhbIbUk33T8Phc+c+IxKgJed65XIITXT9RatxJE94BI2ypFuJc2HhaBg+wbYS4bnpvczGTw4XYPWS/1gnZW0AqABxpkvXs0MDzFbLXI2I810kZtzfSM0NbFdd6zdRTvNTOSioWR9Nmg+vkrNb0eVhw6CkAVl343+9szRyaFoD9og3187d8VCGRKwKKrmreHbuR8y1OBdHsfFQlFNR44sq40qjviWCXqiGL2MPxCMrdpwV43H2zLfvDCku1D8o+w4tcx1bJIWExwN0edeY5PlxAE/UQunh8oyV3PdpavqVSPdyUWwjC7iwWsfHZLjq7WR5yWUxveIV6u/rSgLgRK7ndX6C4/NiT0lCp7+a1Gu3Qs+usC0gFeuTF+iZ13G6eHq3La482ONoXFcSxR/bCj/YJIRI7k6S1VVjoIXYTsU3But75nM3CIdizWXkOn1F3pMqxwWVt1hkrIm5HJHIx3FiJb3m+Ac5jKCo3T6/TTUWA5kBjXsfGjKSSXWv7TVkhyvGj8Cv4otCMYKwMlnILEkuRd/tHS8NRbpfSPa9U/vlh377sU0ej6LC7s2zDzAaxoN4qLH9/S3uRjNg=
before_install:
- openssl aes-256-cbc -K $encrypted_676ca1e73c16_key -iv $encrypted_676ca1e73c16_iv
  -in scripts/codesigning.asc.enc -out scripts/codesigning.asc -d
