sudo: false
language: java
jdk:
- oraclejdk8
- openjdk11
jobs:
  include:
  - stage: deploy
    jdk: oraclejdk8
    script:
    - /scripts/mvn_deploy.sh
script: make default
env:
  global:
  - secure: VrhWb8Tc7n2C/N4sIHcijHWFoO4EPlRiTxzqOBYH4scwAtOYv6JonFPLCT18eE1D0X30783uCgTDqfrbHrrYQKLkltuV16iVcNSKojS9cW/2wRRp56x80nihyXxu246t3VcGl92SQD17yNjFGLQumxJJ3tA+2w99owEX/w4nh6MJ3TDA2zLSEtNnQEMbXw5vgwgwtAnXX6J1hCz0r4r3bsjIhKBhkLfpJ+6qpCEpLHjBB8/Dkn29J3tBqwY8VhOiXX2MqFOQue93Z71G7C89SUoN+ATs/PbVuvZ5nwAGhgTlbj3s0NeMbr5pFpUbpm9YpYAeldggftWJAPOVE50s3ItaK+A6py0Q4hvp4z866Jx0OKV6R/4IqjQ9mzb0WahMC4/+58VV9hIF+CkFHJLdJf4FRS7L6F/1D3S0/3XUrRQlEz+tWEN6Lbzr9mSbrXjB/FYrwmCpBXJucIJvuFxPyFw16l5GuiTGpSXUXGVCf06N/2zC/MHIYrm6DRZ5hab/k0970pZaFwGGOEh+LsQq9fogP0Jwt5ZmJWiteZdy4eSFKYoKkghc1NpLWhO4b5UOK/x2BKjpHE3t/x6iZYW8hoYDuLf22EptmCwhQtB8PJ3BfaZrzJpOdWcPmSz7Upv1/jkRAfkjAyIOuvl6T4aAYQ88+nchAnAb6nSC3WGduY0=
  - secure: UR8Xec+rJrkxswrGjAZPpcqHhAoccP3tgruZCQJ/FW9RteizUc2VN23a/qDsQjARBRlMlgPy2Nhmy9SqRzhWSYbXiuqzYJsBXnUJIC43dPeFoomSOqlNod5Z09IxvRTSR8Z9dCLhjR2TWmwN5iaR3F35SeVx9LjBrzB4QS3EaLavG4VMt1Fh3vdkubj8rq0sdN1Jj11LxCAPKU11KqgQOJkC/GX3czU4EBYKOB2NWunVa7LP3mFG/t5S7Jcixn5a0Vsf8CnQyG18EOz574OB2lGDRfAbITzgFnsHKWEsp4YUzw3vg5ABD8oyYu4brJrI6nu19sG9WkxfmBQiHws9Mm00FAd+c/zqJHswBdJSWAqNyaQjQX/dr2T7Ew6yisi2r+FQC365D5/LtGw8IZ9xKRbcUgvwgQ5jzZip+D4axn/z50ty4WVButQLV0v8k4TCzj1n5RjRHCZTobmb4QE0HqytleMz5jHghKy6nzGDOumXOzZzoeQxdlLm83WKpf3tVktii//Bvz6KQ0Te47m4LRD8HdjndMUu3paMKKKNrLtc4JYF21adkIueb8RvtunTntmn/mP8pb7vMQkB1AkxGbLjICi/gp4J8InZmsBbZLXg2KfjVd++nWWctDLEQ2zhZeSQvC2Lk80sO0Plft85pMQS4hccTrOEMGoWJJ91+0Y=
before_install:
- openssl aes-256-cbc -K $encrypted_0f645401adb0_key -iv $encrypted_0f645401adb0_iv
  -in scripts/codesigning.asc.enc -out scripts/codesigning.asc -d
