language: go
sudo: false
go:
- '1.11'
script:
- env GO111MODULE=on make
after_deploy:
- test $TRAVIS_TAG && scripts/trigger_build.sh cucumber dots-formatter-ruby $TRAVIS_TAG $TRAVIS_API_TOKEN
jobs:
  include:
  - stage: deploy
    go: '1.11'
    before_install:
    - curl -L https://github.com/upx/upx/releases/download/v3.94/upx-3.94-amd64_linux.tar.xz
      | tar Jx
    - export PATH=$PATH:$PWD/upx-3.94-amd64_linux
    script:
    - env GO111MODULE=on make
    - env GO111MODULE=on make .dist-compressed
    - cp dist_compressed/* dist/
deploy:
- provider: releases
  api_key:
    secure: Vsmuq8q+7TFli0h/Ts9vU5Th8w7rKFgSVj9oUZH8VvCFqLxxvxYLp8rRIK58KHvbr0VPeGJ0c2Sxn4B74uu8T1rPEn9CSV8haKNnqsVxxANyiuBvY7jb7+fQeETr+1hQbMaKLPdtnDi8viBts1UL6b80MszhLJdpB0cEWXT8NMt8F0VKy9w5lfg3FI4nqNITYn0b4GXEtpV3wH7XzsMHWl2YUA2MHXKlYNiV8GaO8krrAvIIFEjWykofjcLH3yq0lSK8ybqMsuqEmKieEbGMguru/e08T0T5RWz7LmwCqODIaPPNto8FWkELWR+4Y6td391xxfzftAhBJM5WrgdU0GpI40mLaLWr4MlLhwPyq8g4vPW0oYXeyjTjj9LX276biv8upZtvjNMmxuZFXnEjGqeEEbIZiheCCldttz62bFbBQFjeo5bqokbilRU4iSeqc9lCP8DH6ZHHGaeF4Ciez93zMjg9BS7kNGqcnHxEaOp5Ht3UVdjEKsID4FbXNI3Sk6g4ZjXYx1MVST9NmJFu2gaU95weTWk8id3yeVFgYTIg2HxTvWp5p0dmaN1bX1mHpv4frQRJVWPbZNoRbszoeqEVeCJPE0gVa87SaNnUMOzkK9UzUgXCl56fPlQri2pLXv4GFQEUUNhs9Jl8bPEdcrQnz8LagDzuah3D8gdwpfQ=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    go: '1.11'
    tags: true
- provider: s3
  region: eu-west-2
  bucket: io.cucumber
  skip_cleanup: true
  upload-dir: dots-formatter-go/$TRAVIS_TAG
  local_dir: dist
  on:
    go: '1.11'
    tags: true
  access_key_id:
    secure: CY/heTGk2tyd3JM6QTaG6LZm1RmdFKU6I3U5HU+NtyWgKu1UGWeJot1mJ8utaYTwtQyB3Z/EIBl17iserSBKv48RJwmfTQkYQIZrvh7j4CNX8Sbbyd3MOWr9+9938OnGokg9CK2Jh0nTVphmmP0riL/SKymLqygB6KvSPxZa7H52WoKyXXyGyIrcmopW+WQrybDo/+xAV2W6feqsrTVRmvMTc57FrJZZPCb9Q9lZ3oGBx+6sFH771pSWi35gkqoDHq4D326133ZTtUdGS5pxNhPMZjDVUgNZJri3sYbwwCv2GaQ3TJc05qopywd2bsBclk/e/pjukanCrhrLJImhxY/sp+02cELNgCIMACb3fMlIfD/rOEFlEaKVMJz15P83ke2Mi2GoDW/729OGqURxTXzbFeM4A9MDp4iiffWsFPcExTvZeeYNBo0NoE1ag479ti/Zf0hvVAh6TnRpSI7sKClzZZEwRz576N4rj7Cvt0qyuxRDmTp2ti88B7CqP86YdS73cWSsx5zvDlbOOZxYzSD+745yy+HpZXMygYPqmcszQ+ubXNE4c1iDoWvVYvm/DN+4YtQj86Q15Hh9N1Vl6vOtY06qVp/azOqnZm8fGOd2fiyqxeNQIn6Aqxd6HVVilUaSeyZnnbICvm369N1bnd8SmrPAZeofl84kKA5463g=
  secret_access_key:
    secure: SMrTXBkWtPc/YfUsLZUxhhv6EaayreUJYUhCOGJvxhsaqC4+9svALpWdW0E9pftPLxcUYFVXUQFSrtIqnokorR1pgGgmdN2mP5K1WyZ3mHhwKNFj15SOlwI3jQ0Ts5P9hLAT2mvgaPd5p25VtUgHcNmCaHx0gVdUaJyTVF6qILnRUiAGGvXxPR+h1rik4WCZobCfu8CdJ9STk3FEtN6ZLYSLfp6H2/u9hj3C7bNYRNpCkaJCs4hXoQTH4rYPmgNpnM33vgviI2Fk/1cYpMh7OltKHRDhExXvukO4u31DC33J1PIxx+XfBPInBGNrb/Qm+f8eJrOt75Rh11xqEblagNw36fQFmddUyPTPD86WF2fc/LaiVqmvX4m5GPp9YlIqJ+fVs9ne1Wk+VgV2xpWagSUYk/9DCYGLU6Ckow8yPx4wz+jyZ1le+aciSpdEDsLL1hUNunps8FpY8IaiYlxwxNmd6d+CmOVSrfbCOBuNogl4kpaCoLLtKXdBZbkVMtZDB6QHfRki4eM3ES5OWrrgJC0BAkCeYsZvDNBYuqV/IKSo65SUyxNOd581crugAjJp2G2EiVbFiLDLF5iQDdcFwEOb/4WFoRvMlY/BFYtnBRj0g0fCrJ+XwXGgKWIlrkfuWmrMuj7BKGbp9jD6b5bWqF7LwLi7FruxFICrJXpxWJs=
- provider: s3
  region: eu-west-2
  bucket: io.cucumber
  skip_cleanup: true
  upload-dir: dots-formatter-go/$TRAVIS_BRANCH
  local_dir: dist
  on:
    go: '1.11'
    tags: false
    all_branches: true
  access_key_id:
    secure: CY/heTGk2tyd3JM6QTaG6LZm1RmdFKU6I3U5HU+NtyWgKu1UGWeJot1mJ8utaYTwtQyB3Z/EIBl17iserSBKv48RJwmfTQkYQIZrvh7j4CNX8Sbbyd3MOWr9+9938OnGokg9CK2Jh0nTVphmmP0riL/SKymLqygB6KvSPxZa7H52WoKyXXyGyIrcmopW+WQrybDo/+xAV2W6feqsrTVRmvMTc57FrJZZPCb9Q9lZ3oGBx+6sFH771pSWi35gkqoDHq4D326133ZTtUdGS5pxNhPMZjDVUgNZJri3sYbwwCv2GaQ3TJc05qopywd2bsBclk/e/pjukanCrhrLJImhxY/sp+02cELNgCIMACb3fMlIfD/rOEFlEaKVMJz15P83ke2Mi2GoDW/729OGqURxTXzbFeM4A9MDp4iiffWsFPcExTvZeeYNBo0NoE1ag479ti/Zf0hvVAh6TnRpSI7sKClzZZEwRz576N4rj7Cvt0qyuxRDmTp2ti88B7CqP86YdS73cWSsx5zvDlbOOZxYzSD+745yy+HpZXMygYPqmcszQ+ubXNE4c1iDoWvVYvm/DN+4YtQj86Q15Hh9N1Vl6vOtY06qVp/azOqnZm8fGOd2fiyqxeNQIn6Aqxd6HVVilUaSeyZnnbICvm369N1bnd8SmrPAZeofl84kKA5463g=
  secret_access_key:
    secure: SMrTXBkWtPc/YfUsLZUxhhv6EaayreUJYUhCOGJvxhsaqC4+9svALpWdW0E9pftPLxcUYFVXUQFSrtIqnokorR1pgGgmdN2mP5K1WyZ3mHhwKNFj15SOlwI3jQ0Ts5P9hLAT2mvgaPd5p25VtUgHcNmCaHx0gVdUaJyTVF6qILnRUiAGGvXxPR+h1rik4WCZobCfu8CdJ9STk3FEtN6ZLYSLfp6H2/u9hj3C7bNYRNpCkaJCs4hXoQTH4rYPmgNpnM33vgviI2Fk/1cYpMh7OltKHRDhExXvukO4u31DC33J1PIxx+XfBPInBGNrb/Qm+f8eJrOt75Rh11xqEblagNw36fQFmddUyPTPD86WF2fc/LaiVqmvX4m5GPp9YlIqJ+fVs9ne1Wk+VgV2xpWagSUYk/9DCYGLU6Ckow8yPx4wz+jyZ1le+aciSpdEDsLL1hUNunps8FpY8IaiYlxwxNmd6d+CmOVSrfbCOBuNogl4kpaCoLLtKXdBZbkVMtZDB6QHfRki4eM3ES5OWrrgJC0BAkCeYsZvDNBYuqV/IKSo65SUyxNOd581crugAjJp2G2EiVbFiLDLF5iQDdcFwEOb/4WFoRvMlY/BFYtnBRj0g0fCrJ+XwXGgKWIlrkfuWmrMuj7BKGbp9jD6b5bWqF7LwLi7FruxFICrJXpxWJs=
env:
  global:
    secure: CaSYPrR0VtocNPAsmCVpZ0Ay+T/fNVTDCWeodG8Yb3/eF06W3zbK7Qne/owHTFTBoTZxPLgcqXOa4PojyHBlvJFrahrhXg2pBlnE7NPJHu5bilEba6cE5ZgH00TGrwcFbRu5P524NnINT5gYfHTsE8rLm61rhN52YPYVeovOehX889PAXofdKtweOVROVc9L2LoJ70sQspt//FTzeR/pAoaggLXV56B89Bb15J9rGCoWc938vVN6dpuxuO141Gx5I7GVfJm6EOEpLU4ybmZT8hmjwyy7in1y4Sph21m5U/DqTFF9plcv5Hq8TYKtZHYGjpxyKRwpxeR0Mboez4zpjabJgr+StdkbJi9EELB02iT4BUgoDFkyKiQOrYzeSfGGOSEHWfjMHL6aAg7kQApRyl51tmd0H1Zg56fouLCIlohH3VFPRhIe+yA78aHYYCMjDDLI/7TUc0kdVptaRUTCYGOHhdBmUXOd+ttTGXlvGC/Fqgrdc3Cm3kFMHnR1eu+/CkpbiKfKzny112Eeq1PL9w0hYo7HgNj5XstfgXsFlTZCKNLolL00XghCovfU/RjrwBmmnwfMWfH7ygDF7opeC/6F5d90hiJd02zGm1mvAYmBOrYioFP/4SuZaCvZvhmVC27Q//ktY/7CusiaH3/It1pO7mnejQSGhuvRTArLi+I=
