language: go
sudo: false
go:
- '1.8'
- '1.9'
- '1.10'
- tip
script: make default
jobs:
  include:
  - stage: deploy
    go: '1.10'
    before_install:
      - curl -L https://github.com/upx/upx/releases/download/v3.94/upx-3.94-amd64_linux.tar.xz | tar zx
      - export PATH=$PATH:$PWD/upx-3.94-amd64_linux
    script: 
      - make .dist
      - make .dist-compressed
      # Copy the binaries that compressed successfully over the uncompressed ones
      - cp dist_compressed/* dist/
deploy:
  # Deploy to S3 for tags
  - provider: s3
    region: eu-west-2
    bucket: io.cucumber
    skip_cleanup: true
    upload-dir: gherkin-go/$TRAVIS_TAG
    local_dir: dist
    on:
      go: '1.10'
      tags: true
    secret_access_key:
      secure: D77H5M2C9AtP4qQ0oXCjHOFOKOFHPxNjn9ZFm7yXy8HRWTZ81YfA5SGyxFu9uNcGhbrECb/i2Hm71piJwJzqv6cyRViF4aWRU8H4mv7JiWSx7Rx3kNIV3I8b4RfM3YRhapFR19aQfaJ7xKQ1hk2xofQGD/qFaSbTNSJ6e1JQL/M=
    access_key_id:
      secure: UCr0EuflA1t0XK/MfB5CHcdCrZNizqkWRwe57Tec7yU0DwLYkdKAaux+uIvFAFrYGnt+5wyRjgM+mjD/H9UrE/3EEs5qWP9dV355s5FLwHD6CmjHCUXfu4JE3EeSIN1siKXbAzD6hLdwwIWPHXmVc7bscr9MiKBI5AaN11JtHKU=
  # Deploy to S3 for non-tags
  - provider: s3
    region: eu-west-2
    bucket: io.cucumber
    skip_cleanup: true
    upload-dir: gherkin-go/$TRAVIS_BRANCH
    local_dir: dist
    on:
      go: '1.10'
      tags: false
    secret_access_key:
      secure: D77H5M2C9AtP4qQ0oXCjHOFOKOFHPxNjn9ZFm7yXy8HRWTZ81YfA5SGyxFu9uNcGhbrECb/i2Hm71piJwJzqv6cyRViF4aWRU8H4mv7JiWSx7Rx3kNIV3I8b4RfM3YRhapFR19aQfaJ7xKQ1hk2xofQGD/qFaSbTNSJ6e1JQL/M=
    access_key_id:
      secure: UCr0EuflA1t0XK/MfB5CHcdCrZNizqkWRwe57Tec7yU0DwLYkdKAaux+uIvFAFrYGnt+5wyRjgM+mjD/H9UrE/3EEs5qWP9dV355s5FLwHD6CmjHCUXfu4JE3EeSIN1siKXbAzD6hLdwwIWPHXmVc7bscr9MiKBI5AaN11JtHKU=
