sudo: false
language: java
jdk:
- oraclejdk8
- openjdk9
- openjdk10
- openjdk11
- openjdk-ea
jobs:
  include:
  - stage: deploy
    jdk: openjdk11
    script:
    - "./scripts/mvn_deploy.sh"
script: make default
env:
  global:
  - secure: agxFqlp+zYAqPnNlc43+hYUIuMkruj2yyawD3K+5ObhgXQWHeFbGL2SWrir0sx/ZBEwa8FnSXz80Gox1wEmUKvjzlPiIkyvThmsDvuYbylEWWK7A1qGVk3L/qtRh+dmqsCyebEPzonTChqiObbC5klXBTtM78LiIF5szRi3yt58=
  - secure: iYMzxCDCH3o34ioWYDRrGi5ISf7JVEY6M6fLRq25a733wmrOSAMVvaEtByTGoHwt1FQu2ipfRkLGILFh+CdS8/X7habXfl+ustzsj982ROz9i0p49Oswi2mncvV72EoUUKLof3ePMtRN80yv/OwTUBZfdQH0/PzNo/hyOrZw0V4=
before_install:
- openssl aes-256-cbc -K $encrypted_16c1bf8e2cda_key -iv $encrypted_16c1bf8e2cda_iv
  -in scripts/codesigning.asc.enc -out scripts/codesigning.asc -d
