language: node_js

matrix:
  include:
    - node_js: "8"
    - node_js: "6"
    - node_js: "4"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5373e574ed4e88026838
    on_success: change
    on_failure: always
    on_start: never
