# Please update /.travis/javascript/.travis.yml in the cucumber/cucumber monorepo
# and sync:
#
#     source scripts/functions.sh && rsync_files
#
language: node_js
node_js:
  - 6.11.3
  - 8.6.0

before_install:
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5373e574ed4e88026838
    on_success: change
    on_failure: always
    on_start: never
