# Please update /.travis/ruby/.travis.yml in the cucumber/cucumber monorepo
# and sync:
#
#     source scripts/functions.sh && rsync_files
#
sudo: false
language: ruby

rvm:
  - "2.5.0"
  - "2.4.3"
  - "2.3.6"
  - "2.2.9"
  - "jruby-9.1.13.0"

script: make default