sudo: false
language: java
jdk:
- oraclejdk8
- openjdk11
jobs:
  include:
  - stage: deploy
    jdk: oraclejdk8
    script:
    - ./scripts/mvn_deploy.sh
script: make default
env:
  global:
  - secure: ffY+1yRPpVTyUhYFNZeBWvY9eb+mvKRdSCDDD5+7cwjK2dJXF0OG1KXZ7aP/LZB8npuJffp3SEoTegUEBRlXEMT7Qb+0CGsoM/1TnWv7QxnwHPXhsCH03Ccqvo+TnwAt1Da4ExRIDwbjetDTH4YyhDIXCT1wTMSeyYJyNpIoNKZFg7k/eFP20hEzfVB/WalW1iWjAb7yF6ZrK4evLlJqtrDPXAAVNEpPle9iE15mN70J6FwrTRdJZHnCiMyqEu/fJ1cNoa7QYrrB3mtrswjX/B4Yz17jFRYhat2ND3MXtcJQgcvz6tUDaN8KgltC0t/HyBI5Z30jf7k9Js8v/8Vd+m3B7HRgUOBxRerd/31tethBBfByWUtNbvrvP7JAm/xPSj2CAopC3RzTVO2OlB0IvT8sqKGLyrobBWvAOseyosRaO53/nuCqS0B9vFVidh7K+A0w2JLeg3tt3bELNnae+aIn0eG2WL4fti9Rk1JM4SFNUcik662gGBphNrVPGP3k5sRmg5hNi8X16j/T83N6E2oALjHbhZ2xLJfjQizcA33IN7H4HEZj0r0mfdpY3dCfscxql4EbWc5WKMYqlfbvda+HDqQWfOO4eg9ujlZoDM93ZsmXPTJ4iI5DQaFFHrvdsF6aafNnG39n+TjIuxX3Yrf0TlJ4OVPSg3l6v5cz/mE=
  - secure: ieq+zg6U3ivUlL1Nk+AJHA3syTuXfGxvU2O++yw+RPZSyykcHKdZUyDiy2WpqXVaatWEwhJX2Zb5TkWDy6G8FlLiyywfjeb7zgTQx3Wa8d3bza3+qZ+AwlwzmPRcq9f0H/e/2MCOG6kRg6wZ4PuGfCsxElXo71b8B/ix56x8kSZatjDjqDD65Eyv918Z2xNyQmtTRFjNeEs9s0YE8G+V6G7BHiMmFdEnzam5veNpLx8QLYDl88I8MtbFcsomJaw3ZNGn9dfoyRdR4VTREvFtIbAiEJjn8MZxa8vwR19tuJja4fW97ZzGGr9TVSTv3+WGdQuplnzQmJY+1ZHH4G3WiW7hb3X+8ZT+Gow6093xml+f26ekKCV6GIVt+AlvV+oWviw5QsC0oPYEljRmgPoLVsyxYudKlUjjwwwhd269UxKy7EVYFnaHQpAvBMgFydLPudgqlVLAULBLgyoIB2ZHKQetf7j4CXh8uPoYTUSn8t0CRuJqDT3r1TIr9c8JbbQzlhX6Bg/o0y8M0L8Ou6DhxKiS6KMDr3NZ6WcDQMgFafChRxB0y6bK48c4qbxbw7RviO2t4FONEgYg8gWTJtPhatmEhb/Zaq34G5QRem4hR7N5InZ0t19LNCbAZ1ShWfy3HaKuY7SQqd7YtqtE+Sf8+ZODT5NsZFKFvgAThboFx7U=
before_install:
- openssl aes-256-cbc -K $encrypted_f49147c17f75_key -iv $encrypted_f49147c17f75_iv
  -in scripts/codesigning.asc.enc -out scripts/codesigning.asc -d
