sudo: false
language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "6"

before_install:
- npm i -g npm@latest
script: make default
jobs:
  include:
  - stage: deploy
    node_js: '10'
    deploy:
      skip_cleanup: true
      provider: npm
      email: cukebot@cucumber.io
      api_key:
        secure: hlfJVCSk3YG4GJMr84Ml0qYtUnfuA5s5ZT5mZdNMNkeDpZwxS3jzkX2jh43ARNhnAiosTD8lrbGT6bOEmfH+wRQdqeUa3igr4dEMBQowqvkJSuhznnZQnb/HVrPhIlGduM2/gcySTpu91tD/Wg3N5WwcrNx6gek6+L9jDWszLZs=
      on:
        tags: true
